module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e3e4",
        "on-background": "#191c1d",
        "tertiary-fixed": "#e2dfff",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#00164e",
        "on-tertiary-container": "#a5a2ff",
        "on-surface-variant": "#444651",
        "outline": "#757682",
        "on-secondary-fixed-variant": "#005049",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#c3c0ff",
        "primary": "#00236f",
        "on-primary-fixed-variant": "#264191",
        "tertiary-container": "#2b15c6",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201d",
        "outline-variant": "#c5c5d3",
        "secondary": "#006a61",
        "primary-container": "#1e3a8a",
        "tertiary": "#190093",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4059aa",
        "secondary-fixed": "#89f5e7",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#90a8ff",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#006f66",
        "surface-dim": "#d9dadb",
        "background": "#f8f9fa",
        "secondary-container": "#86f2e4",
        "surface-container-low": "#f3f4f5",
        "primary-fixed": "#dce1ff",
        "surface-bright": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-error": "#ffffff",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};